version: "3.8"

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=atluser
      - MYSQL_PASSWORD=atlpass
      - MYSQL_DATABASE=atl
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: atl
      MYSQL_USER: atluser
      MYSQL_PASSWORD: atlpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
